config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 	# root to: 'messages#create'
 	get '/' => redirect('/messages')
 	get "messages" => "messages#new"
	post "messages" => "messages#create"
	get "messages/api" => "messages#return_mssg_as_json"
	post "messages/api" => "messages#mssg_as_json"
	resources :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	 protect_from_forgery with: :null_session
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	protect_from_forgery except: :mssg_as_json
	def new
	end

	def create
		@message = Message.new(params.require(:messages).permit(:text))
		@message.save
		string = "http://privnote.herokuapp.com/messages/" 
		@message.url = string + @message.id.to_s
		@message.save
	end
	
	def show
		id = params[:id]
		if Message.exists?(id)
			@message = Message.find(id)
			respond_to do |format|
	      		format.html # stays the same
	  			format.json { render json: @message.to_json }
	        	format.xml  { render :xml => @message.to_xml }
	    	end
	    	@message.destroy
	    else 
	    	# message is already destroyed
			@message = Message.new(:text => "The message was destroyed! You can't view it.")
			@message.save
			render :error
		end
		
	end


   	def is_xml?
        request.content_type =~ /xml/
    end

    def is_json?
       request.content_type =~ /json/
	end

	def mssg_as_json
	 	if is_json?
		 	@message = Message.new
@message.text =  params.permit(:message)[:message]
			@message.save
			string = "http://privnote.herokuapp.com/messages/" 
			@message.url = string + @message.id.to_s
			@message.save
			render json: { url: @message[:url] }
	 	elsif is_xml?
	 		@message = Message.new
			@message.text = Nokogiri::XML.fragment(request.body.read).content
	 		@message.save
			string = "http://privnote.herokuapp.com/messages/" 
			@message.url = string + @message.id.to_s
			@message.save
			output = "<url>" + @message.url + "</url>"
			render xml: output
	 	end 
	end


	def return_mssg_as_json
		# in browser
		if Message.exists?(params[:id])
			if @message == Message.find_by(id: params[:id])
			  render json: { message: @message[:text] }
			else
			  render json: {errors: :not_found}, status: :not_found
			end
			@message.destroy
		else 
		   render json: { error: "Error!Message was destroyed!" }
		end
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Privnote</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/messages/api.html.erb
<p>
	API view
</p>

app/views/messages/create.html.erb
<div style="align-content: center;text-align: center;font-size: 460%">
		<p > 
			The URL is: 
		</p>

		<p> 
			<% string = "http://privnote.herokuapp.com" %>
			<%= string+message_path(@message)%>
		</p>

		<p>
			For direct link, click here: <br>
		</p>

		<%= link_to message_path(@message), message_path(@message), data: {confirm: "Click OK to see message" }%>

</div>

app/views/messages/error.html.erb
<h1 style = "text-align: center;font-size: 800%"> Your message was succesfully destroyed. </h1>
<h2 style = "text-align: center;font-size: 300%"> If you didn't open the note, someone opened it before you! </h1>

app/views/messages/new.html.erb
<%= form_with scope: :messages, local: true do |form| %>
  <p style = "text-align: center;font-size: 200%"> 
  		Enter your message here: <br>
  </p>
     
  <div style = "text-align: center">
  		 <%= form.text_area :text, cols: "150", rows: "30" %>
  </div>

  <p style = "text-align: center;">
    <%= form.submit 'Save message', data: { confirm: 'Click ok to confirm creating of message!' } %>
  </p>

<% end %>

app/views/messages/show.html.erb
<p style = "text-align: center;font-size: 400%">
	<b> Your message is: </b> <br>
	<%= @message.text %> <br><br>
		 <!-- <b> Your URL is: </b> <br> 
		<%="#{request.protocol}#{request.host_with_port}#{request.fullpath}" %> -->
</p>